#!/bin/bash
#to add in to crontab (schedule the script at 4 am once per week) enter crontab -e
#and 0 4 * * 1 /path/to/script
#apt-get is the command-line tool for handling packages
#update used to re-synchronize the package index files from their sources.
#upgrade to install the newest versions of all packages currently installed on the system 
#-y automatic yes to prompts. Assume "yes" as answer to all prompts and run non-interactively.

apt-get update && apt-get upgrade -y &> /var/log/update_script.log
